//! Execpolicy rule set generation and injection for T0-4.
//!
//! Writes a `.rules` file (Starlark DSL consumed by `codex_execpolicy`) into
//! the `rules/` subdirectory of a `CODEX_HOME` directory. The app-server
//! auto-loads all `*.rules` files from `<CODEX_HOME>/rules/` at startup (see
//! `codex_core::exec_policy::load_exec_policy`), so writing the file before
//! spawning the server is sufficient to inject the policy.
//!
//! The rule set proves H2: strategy can be下发 and takes effect per
//! tenant/role. `rm` is Forbidden, `ls` is Allow.

use std::path::Path;
use std::path::PathBuf;

use anyhow::Context;
use anyhow::Result;

/// The Starlark DSL content for the Nexus default execpolicy.
///
/// Syntax is defined by `codex_execpolicy::parser::PolicyParser` and the
/// `prefix_rule` builtin. See `codex-rs/execpolicy/src/parser.rs`.
pub const NEXUS_DEFAULT_RULES: &str = r#"# Nexus control-plane execpolicy (T0-4)
# Auto-loaded from <CODEX_HOME>/rules/default.rules

# rm is forbidden — proves destructive commands are blocked by policy.
prefix_rule(
    pattern = ["rm"],
    decision = "forbidden",
    justification = "rm blocked by Nexus execpolicy (T0-4)",
)

# ls is explicitly allowed — proves safe commands pass through.
prefix_rule(
    pattern = ["ls"],
    decision = "allow",
    justification = "ls allowed by Nexus execpolicy (T0-4)",
)
"#;

/// Write the Nexus default `.rules` file to `<codex_home>/rules/default.rules`.
///
/// Returns the full path to the written file.
pub fn write_default_rules(codex_home: &Path) -> Result<PathBuf> {
    let rules_dir = codex_home.join("rules");
    std::fs::create_dir_all(&rules_dir)
        .with_context(|| format!("failed to create rules dir {}", rules_dir.display()))?;
    let rules_path = rules_dir.join("default.rules");
    std::fs::write(&rules_path, NEXUS_DEFAULT_RULES)
        .with_context(|| format!("failed to write {}", rules_path.display()))?;
    Ok(rules_path)
}

/// Write a config.toml to `<codex_home>/config.toml` that points the model
/// provider at a local gateway and uses a ReadOnly sandbox.
pub fn write_config_toml(
    codex_home: &Path,
    gateway_url: &str,
    gateway_token: &str,
) -> Result<PathBuf> {
    let config_path = codex_home.join("config.toml");
    let content = format!(
        r#"# Nexus config (T0-4 + T0-7)
# Generated by nexus-control — do not edit manually.

model_provider = "nexus-gateway"

[model_providers.nexus-gateway]
name = "Nexus Gateway"
base_url = "{gateway_url}"
experimental_bearer_token = "{gateway_token}"
wire_api = "responses"
"#,
    );
    std::fs::write(&config_path, content)
        .with_context(|| format!("failed to write {}", config_path.display()))?;
    Ok(config_path)
}

// ---------------------------------------------------------------------------
// Unit tests — verify the rule set evaluates correctly without an app-server.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use codex_execpolicy::Decision;
    use codex_execpolicy::PolicyParser;

    fn parse_rules() -> codex_execpolicy::Policy {
        let mut parser = PolicyParser::new();
        parser
            .parse("nexus-default.rules", NEXUS_DEFAULT_RULES)
            .expect("rules should parse");
        parser.build()
    }

    fn allow_all(_: &[String]) -> Decision {
        Decision::Allow
    }

    /// AC4.1: `rm -rf /` is Forbidden.
    #[test]
    fn rm_rf_is_forbidden() {
        let policy = parse_rules();
        let cmd: Vec<String> = ["rm", "-rf", "/"].iter().map(|s| s.to_string()).collect();
        let eval = policy.check(&cmd, &allow_all);
        assert_eq!(
            eval.decision,
            Decision::Forbidden,
            "rm -rf / must be forbidden by execpolicy"
        );
        // Verify a policy rule (not just heuristics) matched.
        assert!(
            eval.matched_rules
                .iter()
                .any(|r| matches!(r, codex_execpolicy::RuleMatch::PrefixRuleMatch { .. })),
            "a prefix rule must match rm"
        );
    }

    /// AC4.2: `ls` is Allow.
    #[test]
    fn ls_is_allowed() {
        let policy = parse_rules();
        let cmd: Vec<String> = ["ls"].iter().map(|s| s.to_string()).collect();
        let eval = policy.check(&cmd, &allow_all);
        assert_eq!(
            eval.decision,
            Decision::Allow,
            "ls must be allowed by execpolicy"
        );
        assert!(
            eval.matched_rules
                .iter()
                .any(|r| matches!(r, codex_execpolicy::RuleMatch::PrefixRuleMatch { .. })),
            "a prefix rule must match ls"
        );
    }

    /// AC4.3: Justification is visible in the matched rule.
    #[test]
    fn justification_visible_in_matched_rule() {
        let policy = parse_rules();
        let cmd: Vec<String> = ["rm", "-rf", "/tmp"].iter().map(|s| s.to_string()).collect();
        let eval = policy.check(&cmd, &allow_all);
        for rule in &eval.matched_rules {
            if let codex_execpolicy::RuleMatch::PrefixRuleMatch {
                decision: Decision::Forbidden,
                justification,
                ..
            } = rule
            {
                assert!(
                    justification.as_ref().is_some_and(|j| j.contains("Nexus")),
                    "forbidden rule must carry Nexus justification, got: {justification:?}"
                );
                return;
            }
        }
        panic!("expected a forbidden prefix rule match with justification");
    }

    /// Unmatched command falls through to heuristics (not a policy match).
    #[test]
    fn unmatched_falls_through() {
        let policy = parse_rules();
        let cmd: Vec<String> = ["echo"].iter().map(|s| s.to_string()).collect();
        let eval = policy.check(&cmd, &allow_all);
        // Heuristics fallback should return Allow for echo (not dangerous).
        assert_eq!(eval.decision, Decision::Allow);
        // The only match should be a heuristics match, not a prefix rule.
        assert!(eval.matched_rules.iter().all(|r| matches!(
            r,
            codex_execpolicy::RuleMatch::HeuristicsRuleMatch { .. }
        )));
    }
}
